More updates in support of MySQL * Move to fluent API for parameterized queries * Create service_bindings view * Parameterized aggregate queries for counts are unsupported so we get it done with Flux#count()
Still getting the following exception at startup

2019-07-08T23:30:50,465 ERROR [reactor-tcp-nio-6] i.p.c.t.PoliciesLoader: PoliciesLoader terminated with error
org.springframework.transaction.TransactionSystemException: Could not roll back R2DBC transaction; nested exception is io.r2dbc.spi.R2dbcNonTransientResourceException: unknown message header 3 on command phase
        at org.springframework.data.r2dbc.connectionfactory.R2dbcTransactionManager.lambda$doRollback$9(R2dbcTransactionManager.java:362)
        at reactor.core.publisher.Mono.lambda$onErrorMap$24(Mono.java:3008)